import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Provider } from './components/SessionProvider/Provider'
import HeaderView from '../app/modules/Header/application/HeaderView/page'
import { ReduxProvider } from './store/ReduxProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <Provider>
            <HeaderView  />
            <main>
              {children}
            </main>
          </Provider>
        </ReduxProvider>
      </body>
    </html>
  )
}
